name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      VER: 3.10.0
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd $VER && docker build . --file Dockerfile --tag python-apache:$VER
